# Launch a job template
- hosts: 127.0.0.1
  tasks:
   - name: Launch a job
     awx.awx.job_launch:
       job_template: "Scale Robotshop Node"
       controller_host: "https://9.46.85.62"
       controller_password: "password"
       controller_username: "admin"
       validate_certs: false
     register: job

   - name: Wait for job max 120s
     awx.awx.job_wait:
       validate_certs: false
       controller_password: "password"
       controller_username: "admin"
       job_id: "{{ job.id }}"
       timeout: 120
