- hosts: all
  module_defaults:
    group/k8s:
      host: https://api.b-robotshop-on-ocp.cp.fyre.ibm.com:6443
      validate_certs: no
  tasks:
  - name: Obtain access token
    k8s_auth:
      username:  kubeadmin
      password: "{{password}}"
    register: k8s_auth_results
  - name: Create a namespace with token
    k8s:
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      name: examplespace
      kind: Namespace
      state: present
  - name: Scale deployment up, and extend timeout
    k8s_scale:
     api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
     api_version: v1
     kind: Deployment
     name: catalogue
     namespace: robot-shop
     replicas: 3
     wait_timeout: 60
