- hosts: all
  gather_facts: no
  vars_files:
    - variables.yaml
  tasks:
  - name: install pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 
  - name: delete a pod
    k8s:
      api_version: v1
      kind: Pod
      namespace: "{{namespace}}"
      name: "{{name}}"
      state: absent
